### ISSUE TITLE
main() is missing

### ISSUE THREAD

**Issue by PeterSommerlad** [hatcat/StandardAsteroids#1]
Hi,

I managed to compile (except for input so far), the reference implementation and asteroids on my mac using X11. However, the main() function you showed is missing so far from the codebase. I wonder if you reused the main() provided in the N3888/P0267 reference implementation and modified that one to accommodate your game?

X11 Input will require some modification to the reference implementation of N3888 to also accept keyboard events ( hacking around so far, might require a lot more to make it useful beyond asteroids). However, it is like being transported 25 years back in time, which might have been the last time I actually wrote Xlib programs (mostly toy examples then). 

Here is my main so far, where at lest the asteroids are moving around:

#include "io2d.h"
#include "Game.h"
#include "Constants.h"
int main() {
	using namespace asteroids;
	using namespace std::experimental::io2d;
	auto ds = make_display_surface(static_cast<int>(playing_field_width), static_cast<int>(playing_field_height), format::argb32, scaling::letterbox, refresh_rate::as_fast_as_possible, 30.0);
	game thegame;
	ds.draw_callback([&](display_surface&surface){thegame.update(surface);});
	return ds.begin_show();
}

**Comment by hatcat** [comment]
The reference implementation is supplied as an executable image rather than a library (I'm working on that over the weekend) so the Asteroids code is a library. You are correct about the modifications.

Keyboard input will have to be the subject of another paper - Brett Searles has proposed something, but there is no reference implementation, and it's also a bit heavyweight. It isn't really suitable for this sort of thing.

Your main() looks fine! After I've updated the reference implementation, I'll add a main function to this code.

Cheers,
G
